# Generated by Django 2.0 on 2021-01-05 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('file_name', models.CharField(max_length=100, verbose_name='文件名称')),
                ('file_cover', models.ImageField(upload_to='', verbose_name='文件封面')),
                ('file_uid', models.UUIDField(blank=True, null=True, verbose_name='文件uid')),
                ('file', models.FileField(upload_to='', verbose_name='文件')),
                ('file_size', models.CharField(max_length=100, verbose_name='文件大小')),
            ],
            options={
                'verbose_name': '资源中心',
                'verbose_name_plural': '资源中心',
                'db_table': 'resource_center',
            },
        ),
    ]
