# Generated by Django 2.0 on 2021-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100, verbose_name='用户名字')),
                ('user_tel', models.CharField(max_length=11, verbose_name='用户电话')),
                ('user_pwd', models.CharField(max_length=20, verbose_name='用户密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': '用户',
            },
        ),
    ]
