# Generated by Django 2.0 on 2021-01-07 03:23

import case.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20210107_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=case.utils.file_upload_path, verbose_name='文件'),
        ),
    ]
