# Generated by Django 2.0 on 2021-01-07 08:31

import case.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20210107_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('class_nums', models.IntegerField(default=30, verbose_name='班级人数')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('stu_id', models.CharField(default=case.utils.stu_id, max_length=18, unique=True, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('stu_age', models.IntegerField(verbose_name='学生年龄')),
                ('stu_sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='学生性别')),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stu_class', to='case.ClassModel', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('tea_id', models.CharField(default=case.utils.tea_id, max_length=18, unique=True, verbose_name='教师编号')),
                ('tea_name', models.CharField(max_length=50, verbose_name='教师名称')),
                ('tea_sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='教师性别')),
                ('tea_age', models.IntegerField(blank=True, null=True, verbose_name='教师年龄')),
                ('tea_class', models.ManyToManyField(to='case.ClassModel', verbose_name='所教班级')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'teacher',
            },
        ),
    ]
