# Generated by Django 2.0 on 2021-01-13 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('enabled', models.BooleanField(default=1, verbose_name='是否有效')),
                ('parent_id', models.IntegerField(null=True, verbose_name='根节点')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='object', to='tree.ResourceModel', verbose_name='评论对象')),
                ('content', models.CharField(max_length=1800, verbose_name='评论内容')),
                ('like_nums', models.IntegerField(default=0, verbose_name='点赞数')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'commit',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='IndexPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('enabled', models.BooleanField(default=1, verbose_name='是否有效')),
                ('package_name', models.CharField(max_length=50, verbose_name='资源包名称')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('cover', models.CharField(max_length=120, verbose_name='封面')),
                ('like_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='点赞数')),
                ('collect_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数')),
                ('order_on', models.IntegerField(default=0, verbose_name='顺序')),
            ],
            options={
                'verbose_name': '资源包',
                'verbose_name_plural': '资源包',
                'db_table': 'resource_package',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('enabled', models.BooleanField(default=1, verbose_name='是否有效')),
                ('resource_name', models.CharField(max_length=50, verbose_name='资源名称')),
                ('resource_type', models.IntegerField(choices=[(0, '图片'), (1, '音频'), (2, '视频')], verbose_name='资源类型')),
                ('cover', models.CharField(max_length=120, verbose_name='封面')),
                ('status', models.CharField(default='N', max_length=1, verbose_name='资源状态:(Y:已上架,N:未上架,D:已下架)')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'db_table': 'resource',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('enabled', models.BooleanField(default=1, verbose_name='是否有效')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='用户id')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('user_sex', models.IntegerField(default=0, verbose_name='用户性别')),
                ('user_phone', models.CharField(max_length=11, unique=True, verbose_name='用户电话')),
                ('user_pwd', models.CharField(max_length=32, verbose_name='用户密码')),
                ('avatar', models.CharField(max_length=120, verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='indexpackage',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource', to='tree.ResourceModel', verbose_name='资源'),
        ),
        migrations.AddField(
            model_name='commitmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='tree.UserModel', verbose_name='用户'),
        ),
    ]
